name: Python App CI & Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & push Docker image
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: manthan010/dev-ops-git         # replace with your DockerHub repo/image
          tags: v1,latest            # tags for your image
          registry: docker.io        # replace if using custom registry
          dockerfile: Dockerfile.ci     # your Dockerfile name
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
